import { ColorPalette, LogoSymbol, StylePreset } from './types';

export const COLOR_PALETTES: ColorPalette[] = [
  {
    id: 'midnight-gold',
    name: 'Midnight Gold (Luxury)',
    primary: 'text-[#E5C158]',
    secondary: 'text-[#FFF2CD]',
    accent: 'text-[#9A7D2C]',
    background: 'bg-[#111111]',
    textPrimary: 'text-[#E5C158]',
    textSecondary: 'text-[#F5F5F5]',
    darkContrast: true,
    bgHex: '#111111',
    primaryHex: '#E5C158',
    secondaryHex: '#FFF2CD',
    accentHex: '#9A7D2C',
  },
  {
    id: 'nord-blue',
    name: 'Nordic Clean (SaaS)',
    primary: 'text-[#0052FF]',
    secondary: 'text-[#5A8FFF]',
    accent: 'text-[#E6EFFF]',
    background: 'bg-[#F4F7FF]',
    textPrimary: 'text-[#091E42]',
    textSecondary: 'text-[#626F84]',
    darkContrast: false,
    bgHex: '#F4F7FF',
    primaryHex: '#0052FF',
    secondaryHex: '#5A8FFF',
    accentHex: '#E6EFFF',
  },
  {
    id: 'rust-clay',
    name: 'Clay & Sage (Organic)',
    primary: 'text-[#C96F53]',
    secondary: 'text-[#4A7055]',
    accent: 'text-[#ECCCA2]',
    background: 'bg-[#FCF9F5]',
    textPrimary: 'text-[#2D221E]',
    textSecondary: 'text-[#5E625F]',
    darkContrast: false,
    bgHex: '#FCF9F5',
    primaryHex: '#C96F53',
    secondaryHex: '#4A7055',
    accentHex: '#ECCCA2',
  },
  {
    id: 'cyberpunk',
    name: 'Vapor Wave (Creative)',
    primary: 'text-[#FF2A85]',
    secondary: 'text-[#05FFD2]',
    accent: 'text-[#FFD700]',
    background: 'bg-[#0E061E]',
    textPrimary: 'text-[#05FFD2]',
    textSecondary: 'text-[#E6B6FF]',
    darkContrast: true,
    bgHex: '#0E061E',
    primaryHex: '#FF2A85',
    secondaryHex: '#05FFD2',
    accentHex: '#FFD700',
  },
  {
    id: 'classic-ink',
    name: 'Classic Ink (Editorial)',
    primary: 'text-[#0F0F0F]',
    secondary: 'text-[#7B0B0C]',
    accent: 'text-[#6B7280]',
    background: 'bg-[#FFFFFF]',
    textPrimary: 'text-[#0F0F0F]',
    textSecondary: 'text-[#4B5563]',
    darkContrast: false,
    bgHex: '#FFFFFF',
    primaryHex: '#0F0F0F',
    secondaryHex: '#7B0B0C',
    accentHex: '#6B7280',
  },
  {
    id: 'forest-moss',
    name: 'Forest Canopy (Zen)',
    primary: 'text-[#1F4E37]',
    secondary: 'text-[#CCA43B]',
    accent: 'text-[#ECF3ED]',
    background: 'bg-[#F2F5F3]',
    textPrimary: 'text-[#1B2B21]',
    textSecondary: 'text-[#5C6E62]',
    darkContrast: false,
    bgHex: '#F2F5F3',
    primaryHex: '#1F4E37',
    secondaryHex: '#CCA43B',
    accentHex: '#ECF3ED',
  },
  {
    id: 'neon-dark',
    name: 'Neon Grid (Terminal)',
    primary: 'text-[#39FF14]',
    secondary: 'text-[#E0E0E0]',
    accent: 'text-[#00E5FF]',
    background: 'bg-[#000000]',
    textPrimary: 'text-[#39FF14]',
    textSecondary: 'text-[#888888]',
    darkContrast: true,
    bgHex: '#000000',
    primaryHex: '#39FF14',
    secondaryHex: '#E0E0E0',
    accentHex: '#00E5FF',
  }
];

export const SYMBOLS: LogoSymbol[] = [
  // Core / Professional
  { id: 'Layers', name: 'Premium Layers', category: 'core' },
  { id: 'Sparkles', name: 'Creative Sparkles', category: 'core' },
  { id: 'VintageCar', name: 'Vintage Carriage', category: 'core' },
  { id: 'Crown', name: 'Royal Crown', category: 'core' },
  { id: 'Gem', name: 'Luxury Jewel', category: 'core' },
  { id: 'Shield', name: 'Trust Guard', category: 'core' },
  { id: 'Flame', name: 'Energy Core', category: 'core' },

  // Tech / Digital
  { id: 'Cpu', name: 'Neural Processor', category: 'tech' },
  { id: 'Database', name: 'Big Data', category: 'tech' },
  { id: 'Globe', name: 'Global Network', category: 'tech' },
  { id: 'Zap', name: 'Velocity Bolt', category: 'tech' },
  { id: 'Atom', name: 'Molecular Atom', category: 'tech' },
  { id: 'Terminal', name: 'Shell Terminal', category: 'tech' },

  // Abstract / Geometric
  { id: 'Hexagon', name: 'Structural Hex', category: 'abstract' },
  { id: 'Compass', name: 'Precision Guide', category: 'abstract' },
  { id: 'Infinity', name: 'Infinity Loom', category: 'abstract' },
  { id: 'Box', name: 'Isometric Cuboid', category: 'abstract' },
  { id: 'CircleDot', name: 'Absolute Center', category: 'abstract' },
  { id: 'Crosshair', name: 'Focus Finder', category: 'abstract' },

  // Retail & Artisanal
  { id: 'Coffee', name: 'Artisan Coffee', category: 'retail' },
  { id: 'ShoppingBag', name: 'Retail Atelier', category: 'retail' },
  { id: 'Wine', name: 'Fine Sommelier', category: 'retail' },
  { id: 'Package', name: 'Craft Logistics', category: 'retail' },
  { id: 'Scissors', name: 'Design Tailor', category: 'retail' },
  { id: 'Key', name: 'Secret Custody', category: 'retail' },

  // Nature & Wellbeing
  { id: 'Leaf', name: 'Organic Leaf', category: 'nature' },
  { id: 'Sun', name: 'Solar Energy', category: 'nature' },
  { id: 'Moon', name: 'Nocturnal Calm', category: 'nature' },
  { id: 'Sprout', name: 'Seed Sprout', category: 'nature' },
  { id: 'Wind', name: 'Aerodynamic draft', category: 'nature' },
  { id: 'Heart', name: 'Wellness Center', category: 'nature' }
];

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'luxury-premium',
    name: 'Classique Luxury',
    description: 'Elegant monogram layout styled with high-contrast luxury serif family and real golden tones.',
    config: {
      brandName: 'AURELIA',
      tagline: 'HAUTE RELEFS',
      layout: 'badge',
      fontFamily: 'cinzel',
      taglineFontFamily: 'sans',
      fontTracking: 'widest',
      taglineTracking: 'widest',
      colorPaletteId: 'midnight-gold',
      iconName: 'Crown',
      iconSize: 45,
      iconRotation: 0,
      iconStrokeWidth: 1.5,
      badgeShape: 'hexagon',
      textUppercase: true,
      taglineUppercase: true,
    }
  },
  {
    id: 'modern-saas',
    name: 'Clean SaaS',
    description: 'Minimalist tech layout using precise geometric shapes, modern typography, and vibrant blue.',
    config: {
      brandName: 'synthex',
      tagline: 'AI OPERATIONS ENGINE',
      layout: 'horizontal',
      fontFamily: 'space',
      taglineFontFamily: 'mono',
      fontTracking: 'normal',
      taglineTracking: 'widest',
      colorPaletteId: 'nord-blue',
      iconName: 'Cpu',
      iconSize: 32,
      iconRotation: 45,
      iconStrokeWidth: 2,
      badgeShape: 'none',
      textUppercase: false,
      taglineUppercase: true,
    }
  },
  {
    id: 'atelier-craft',
    name: 'Artisan Atelier',
    description: 'Clay-toned natural elements blended with a warm editorial serif, curated for sustainable brands and cafes.',
    config: {
      brandName: 'Earth & Oak',
      tagline: 'ORGANIC BOTANICALS',
      layout: 'vertical',
      fontFamily: 'serif',
      taglineFontFamily: 'sans',
      fontTracking: 'normal',
      taglineTracking: 'wide',
      colorPaletteId: 'rust-clay',
      iconName: 'Leaf',
      iconSize: 48,
      iconRotation: -15,
      iconStrokeWidth: 1.5,
      badgeShape: 'none',
      textUppercase: false,
      taglineUppercase: true,
    }
  },
  {
    id: 'neon-terminal',
    name: 'Terminal Dev',
    description: 'Brutalist cyberpunk developer branding utilizing intense lime contrast, cyber-structures, and monospace fonts.',
    config: {
      brandName: 'ROOT.SYS',
      tagline: 'DECENTRALIZED ROOT',
      layout: 'horizontal',
      fontFamily: 'mono',
      taglineFontFamily: 'mono',
      fontTracking: 'widest',
      taglineTracking: 'normal',
      colorPaletteId: 'neon-dark',
      iconName: 'Terminal',
      iconSize: 30,
      iconRotation: 0,
      iconStrokeWidth: 2,
      badgeShape: 'square',
      textUppercase: true,
      taglineUppercase: true,
    }
  },
  {
    id: 'creative-vapor',
    name: 'Vapor Creative',
    description: 'Vibrant neon gradients with high-energy colors designed for agency studios, portfolios, and tech labs.',
    config: {
      brandName: 'VIVID',
      tagline: 'CREATIVE LABS',
      layout: 'vertical',
      fontFamily: 'display',
      taglineFontFamily: 'display',
      fontTracking: 'widest',
      taglineTracking: 'widest',
      colorPaletteId: 'cyberpunk',
      iconName: 'Sparkles',
      iconSize: 50,
      iconRotation: 12,
      iconStrokeWidth: 2,
      badgeShape: 'circle',
      textUppercase: true,
      taglineUppercase: true,
    }
  }
];
